[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "pykada"
dynamic = ["version"]
authors = [
  { name="Ryan Malley", email="ryanmalley101@gmail.com" },
]
description = "A handy library for interacting with Verkada APIs."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.32.3",
    "python-dotenv>=1.1.0",
    "typeguard>=4.4.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4.1",
    "numpy>=2.2.6",
    "pandas>=2.3.2",
    "termcolor>=3.1.0",
    "python-vlc>=3.0.21203",
]
docs = [
    "sphinx>=8.0",
    "furo>=2024.8.6",
    "sphinx-autodoc-typehints>=2.3",
]

[tool.hatch.build.targets.wheel]
packages = ["pykada"]

[tool.hatch.version]
path = "pykada/__init__.py"