WEEKDAY_ENUM = {
    "SUNDAY": "SU",
    "MONDAY": "MO",
    "TUESDAY": "TU",
    "WEDNESDAY": "WE",
    "THURSDAY": "TH",
    "FRIDAY": "FR",
    "SATURDAY": "SA",
}
FREQUENCY_ENUM = {
    "DAILY": "DAILY",
    "WEEKLY": "WEEKLY",
    "MONTHLY": "MONTHLY",
    "YEARLY": "YEARLY"
}
DOOR_STATUS_ENUM = {
    "LOCKED": "locked",
    "CARD_AND_CODE": "card_and_code",
    "ACCESS_CONTROLLED": "access_controlled",
    "UNLOCKED": "unlocked"
}
SENSOR_FIELD_ENUM = {
    "HUMIDITY": "humidity",
    "MOTION": "motion",
    "NOISE_LEVEL": "noise_level",
    "PM_2_5": "pm_2_5",
    "PM_4_0": "pm_4_0",
    "PM_1_0_0": "pm_1_0_0",
    "TAMPER": "tamper",
    "TEMPERATURE": "temperature",
    "TVOC_SV11": "tvoc",
    "USA_AIR_QUALITY_INDEX": "usa_air_quality_index",
    "VAPE_INDEX": "vape_index",
    "CARBON_DIOXIDE": "carbon_dioxide",
    "CARBON_MONOXIDE": "carbon_monoxide",
    "BAROMETRIC_PRESSURE": "barometric_pressure",
    "FORMALDEHYDE": "formaldehyde",
    "AMBIENT_LIGHT": "ambient_light",
    "TVOC_INDEX(SV23/SV25)": "tvoc_index",
    "HEAT_INDEX": "heat_index"
}
VALID_ACCESS_EVENT_TYPES_ENUM = {
    "DOOR_OPENED": "door_opened",
    "DOOR_REJECTED": "door_rejected",
    "DOOR_GRANTED": "door_granted",
    "DOOR_FORCED_OPEN": "door_forced_open",
    "DOOR_HELD_OPEN": "door_held_open",
    "DOOR_TAILGATING": "door_tailgating",
    "DOOR_CROWD_DETECTION": "door_crowd_detection",
    "DOOR_TAMPER": "door_tamper",
    "DOOR_POI_DETECTION": "door_poi_detection",
    "DOOR_INITIALIZED": "door_initialized",
    "DOOR_ARMED": "door_armed",
    "DOOR_ARMED_BUTTON_PRESSED": "door_armed_button_pressed",
    "DOOR_AUX_UNLOCK": "door_aux_unlock",
    "DOOR_LOCKED": "door_locked",
    "DOOR_UNLOCKED": "door_unlocked",
    "DOOR_UNARMED_EVENT": "door_unarmed_event",
    "DOOR_CODE_ENTERED_EVENT": "door_code_entered_event",
    "DOOR_BUTTON_PRESS_ENTERED_EVENT": "door_button_press_entered_event",
    "DOOR_ACU_STARTUP": "door_acu_startup",
    "DOOR_LOCK_STATE_CHANGED": "door_lock_state_changed",
    "DOOR_LOCKDOWN": "door_lockdown",
    "DOOR_AUXINPUT_CHANGE_STATE": "door_auxinput_change_state",
    "DOOR_AUXINPUT_HELD": "door_auxinput_held",
    "DOOR_LOW_BATTERY": "door_low_battery",
    "DOOR_CRITICAL_BATTERY": "door_critical_battery",
    "DOOR_MOBILE_NFC_SCAN_ACCEPTED": "door_mobile_nfc_scan_accepted",
    "DOOR_MOBILE_NFC_SCAN_REJECTED": "door_mobile_nfc_scan_rejected",
    "DOOR_USER_DATABASE_CORRUPT": "door_user_database_corrupt",
    "DOOR_KEYCARD_ENTERED_ACCEPTED": "door_keycard_entered_accepted",
    "DOOR_KEYCARD_ENTERED_REJECTED": "door_keycard_entered_rejected",
    "DOOR_CODE_ENTERED_ACCEPTED": "door_code_entered_accepted",
    "DOOR_CODE_ENTERED_REJECTED": "door_code_entered_rejected",
    "DOOR_REMOTE_UNLOCK_ACCEPTED": "door_remote_unlock_accepted",
    "DOOR_REMOTE_UNLOCK_REJECTED": "door_remote_unlock_rejected",
    "DOOR_PRESS_TO_EXIT_ACCEPTED": "door_press_to_exit_accepted",
    "DOOR_BLE_UNLOCK_ATTEMPT_ACCEPTED": "door_ble_unlock_attempt_accepted",
    "DOOR_BLE_UNLOCK_ATTEMPT_REJECTED": "door_ble_unlock_attempt_rejected",
    "DOOR_ACU_OFFLINE": "door_acu_offline",
    "DOOR_FIRE_ALARM_TRIGGERED": "door_fire_alarm_triggered",
    "DOOR_FIRE_ALARM_RELEASED": "door_fire_alarm_released",
    "DOOR_ACU_FIRE_ALARM_TRIGGERED": "door_acu_fire_alarm_triggered",
    "DOOR_ACU_FIRE_ALARM_RELEASED": "door_acu_fire_alarm_released",
    "DOOR_SCHEDULE_TOGGLE": "door_schedule_toggle",
    "DOOR_ACU_DPI_CUT": "door_acu_dpi_cut",
    "DOOR_ACU_DPI_SHORT": "door_acu_dpi_short",
    "DOOR_ACU_REX_CUT": "door_acu_rex_cut",
    "DOOR_ACU_REX_SHORT": "door_acu_rex_short",
    "DOOR_ACU_REX2_CUT": "door_acu_rex2_cut",
    "DOOR_ACU_REX2_SHORT": "door_acu_rex2_short",
    "DOOR_ACU_AUXINPUT_CUT": "door_acu_auxinput_cut",
    "DOOR_ACU_AUXINPUT_SHORT": "door_acu_auxinput_short",
    "DOOR_LOCKDOWN_DEBOUNCED": "door_lockdown_debounced",
    "DOOR_LP_PRESENTED_ACCEPTED": "door_lp_presented_accepted",
    "DOOR_LP_PRESENTED_REJECTED": "door_lp_presented_rejected",
    "DOOR_APB_DOUBLE_ENTRY": "door_apb_double_entry",
    "DOOR_APB_DOUBLE_EXIT": "door_apb_double_exit",
    "ALL_ACCESS_GRANTED": "all_access_granted",
    "ALL_ACCESS_REJECTED": "all_access_rejected",
    "DOOR_AUXOUTPUT_ACTIVATED": "door_auxoutput_activated",
    "DOOR_AUXOUTPUT_DEACTIVATED": "door_auxoutput_deactivated"
}
VALID_CARD_TYPES_ENUM = {
    "STANDARD_26_BIT_WIEGAND": "Standard 26-bit Wiegand",
    "HID_37_BIT": "HID 37-bit",
    "HID_37_BIT_NO_FACILITY_CODE": "HID 37-bit No Facility Code",
    "HID_34_BIT": "HID 34-bit",
    "CASI_RUSCO_40_BIT": "Casi Rusco 40-Bit",
    "HID_CORPORATE_1000_35": "HID Corporate 1000-35",
    "HID_CORPORATE_1000_48": "HID Corporate 1000-48",
    "HID_ICLASS": "HID iClass",
    "DESFIRE_CSN": "DESFire CSN",
    "VERKADA_DESFIRE": "Verkada DESFire",
    "DESFIRE_40X": "DESFire 40X",
    "APPLE_WALLET_PASS": "Apple Wallet Pass",
    "MIFARE_4_BYTE_CSN": "MiFare 4-Byte (32 bit) CSN",
    "MDC_CUSTOM_64_BIT": "MDC Custom 64-bit",
    "HID_36_BIT_KEYSCAN": "HID 36-bit Keyscan",
    "HID_33_BIT_DSX": "HID 33-bit DSX",
    "HID_33_BIT_RS2": "HID 33-bit RS2",
    "HID_36_BIT_SIMPLEX": "HID 36-bit Simplex",
    "CANSEC_37_BIT": "Cansec 37-bit",
    "CREDIT_CARD_BIN_NUMBER": "Credit Card BIN Number",
    "KANTECH_XSF": "Kantech XSF",
    "SCHLAGE_34_BIT": "Schlage 34-bit",
    "SCHLAGE_37_BIT": "Schlage 37-bit",
    "RBH_50_BIT": "RBH 50-bit",
    "GUARDALL_G_PROX_II_36_BIT": "Guardall G-Prox II 36-bit",
    "AMAG_32_BIT": "AMAG 32-bit",
    "SECURITAS_37_BIT": "Securitas 37-bit",
    "KASTLE_32_BIT": "Kastle 32-bit",
    "POINTGUARD_MDI_37_BIT": "PointGuard MDI 37-bit",
    "BLACKBOARD_64_BIT": "Blackboard 64-bit",
    "IDM_64_BIT": "IDm 64-bit",
    "CONTINENTAL_36_BIT": "Continental 36-bit",
    "AWID_34_BIT": "AWID 34-bit",
    "LICENSE_PLATE": "License Plate",
    "HID_INFINITY_37_BIT": "HID Infinity 37-bit",
    "HID_CERIDIAN_26_BIT": "HID Ceridian 26-bit",
    "ICLASS_35_BIT": "iClass 35-bit",
    "ANDOVER_CONTROLS_37_BIT": "Andover Controls 37-bit"
}
VALID_OCCUPANCY_TRENDS_INTERVALS_ENUM = {
    "15_MINUTES": "15_minutes",
    "1_HOUR": "1_hour",
    "6_HOURS": "6_hours",
    "12_HOURS": "12_hours",
    "1_DAY": "1_day",
    "30_DAYS": "30_days"
}
VALID_OCCUPANCY_TRENDS_TYPES_ENUM = {
    "PERSON": "person",
    "VEHICLE": "vehicle"
}
VALID_CLOUD_BACKUP_VIDEO_QUALITY_ENUM = {
    "STANDARD_QUALITY": "STANDARD_QUALITY",
    "HIGH_QUALITY": "HIGH_QUALITY",
}
VALID_CLOUD_BACKUP_VIDEO_TO_UPLOAD_ENUM = {
    "ALL": "ALL",
    "MOTION": "MOTION",
}
VALID_IMAGE_RESOLUTION_ENUM = {
    "LOW_RES": "low-res",
    "HI_RES": "hi-res",
}
